version: "3.8"
services:
  tonos:
    image: tonlabs/local-node
    ports:
      - "8080:80"
  dev:
    tty: true
    stdin_open: true
    build:
      dockerfile: ./docker_dev/Dockerfile
      context: .
    volumes:
      - .:/app
      - bundle_volume:/bundle
    env_file:
      - ./docker_dev/.env_docker
    depends_on:
      - tonos

volumes:
  bundle_volume:
    driver: local
